views:
  advertisements:
    config:
      set_defaults: true
      rejected_field_names: 'name slug published_date'
    new:
      meta_header:
        type: 'header'
        text: 'Meta Data'
      name:
        label: 'Name'
        type: 'string'
      tags:
        label: 'Tags'
        type: 'association'
      published_date:
        label: 'Published Date'
        type: 'datepicker'
      ad_header:
        type: 'header'
        text: 'Ad'
      image:
        label: 'Image'
        type: 'image'
        size: ['627','560']
        required: true
      url:
        label: 'URL'
        type: 'string'
        required: true
      title:
        label: 'Title'
        type: 'string'
        required: true
      text:
        label: 'Text'
        type: 'text'
        required: true
    list:
      name:
        label: 'Name'
        type: 'string'
      image:
        label: 'Image'
        type: 'image'
      tags:
        label: 'Tags'
        type: 'unlinked_list'
