views:
  articles:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      name:
        label: 'Name'
        type: 'string'
        maxlength: '70'
        hint: 'Limited to 70 characters'
      description:
        label: 'Description'
        type: 'text'
        maxlength: '160'
        hint: 'Limited to 160 characters'
        required: true
      user:
        label: 'Author'
        type: 'dropdown'
        required: true
      category:
        label: 'Category'
        type: 'dropdown'
      tags:
        label: 'Tags'
        type: 'association'
      published_date:
        label: 'Published Date'
        type: 'datepicker'

      # images_header:
      #   type: 'header'
      #   text: 'Images'
      # landscape_image:
      #   label: 'Landscape Image'
      #   type: 'image'
      #   size: ['2048','1024']
      #   required: true
      # card_image:
      #   label: 'Card Image'
      #   type: 'image'
      #   size: ['1100','900']
      #   required: true
      # image_alt:
      #   label: 'Image Description'
      #   type: 'string'
      #   maxlength: '40'
      #   hint: 'Limited to 40 characters'
      #   required: true

      # details_header:
      #   type: 'header'
      #   text: 'Details'
      # long_title:
      #   label: 'Long Title'
      #   type: 'string'
      #   maxlength: '85'
      #   hint: 'Limited to 85 characters'
      #   required: true
      # long_summary:
      #   label: 'Long Summary'
      #   type: 'rich'
      #   required: true
      # body:
      #   label: 'Article Body'
      #   type: 'rich'
      #   required: true
