views:
  defaults:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    basiclist:
      name:
        label: 'Short Title'
        type: 'string'
      published_date:
        label: 'Published'
        type: 'string'
    list:
      name:
        label: 'Title'
        type: 'string'
      category:
        label: 'Category'
        type: 'string'
        scope: 'name'
      tags:
        label: 'Tags'
        type: 'unlinked_list'
      published_date:
        label: 'Published'
        type: 'string'
