views:
  discussions:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      meta_header:
        type: 'header'
        text: 'Meta'
      name:
        label: 'Title'
        icon: 'heading'
        type: 'string'
        maxlength: '70'
        hint: 'Limited to 70 characters'
      description:
        label: 'Description'
        icon: 'text width'
        type: 'text'
        maxlength: '160'
        hint: 'Limited to 160 characters'
        required: true
      user:
        label: 'Author'
        icon: 'user'
        type: 'dropdown'
        required: true
      category:
        label: 'Category'
        icon: 'folder'
        type: 'dropdown'
      tags:
        label: 'Tags'
        icon: 'tag'
        type: 'association'
      published_date:
        label: 'Published Date'
        icon: 'calendar'
        type: 'datepicker'

      social_header:
        type: 'header'
        text: 'Social Sharing'
      social_image:
        label: 'Social Media Image'
        type: 'image'
        icon: 'image'
        size: ['2048','1024']
      social_alt:
        label: 'Image Description'
        icon: 'image'
        type: 'string'
        maxlength: '40'
        hint: 'Describe the image for visually impaired (i.e. a horse eating a carrot).'
