views:
  discussions:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      meta_header:
        type: 'header'
        text: 'Meta Data'
      name:
        label: 'Short Title'
        type: 'string'
        maxlength: '70'
        hint: 'Limited to 70 characters'
      description:
        label: 'Short Summary'
        type: 'text'
        maxlength: '160'
        hint: 'Limited to 160 characters'
        required: true
      category:
        label: 'Category'
        type: 'dropdown'
      tags:
        label: 'Tags'
        type: 'association'
      published_date:
        label: 'Published Date'
        type: 'datepicker'
      user:
        label: 'Author'
        type: 'dropdown'
        required: true

      social_header:
        type: 'header'
        text: 'Social Sharing'
      long_title:
        label: 'Title'
        type: 'string'
        maxlength: '85'
        hint: 'Limited to 85 characters'
      long_summary:
        label: 'Summary'
        type: 'text'
