views:
  entries_discussions:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      meta_header:
        type: 'header'
        text: 'Meta'
      name:
        label: 'Title'
        type: 'string'
        maxlength: '70'
        hint: 'Limited to 70 characters'
      description:
        label: 'Description'
        type: 'text'
        maxlength: '160'
        hint: 'Limited to 160 characters'
        required: true
      user:
        label: 'Author'
        type: 'dropdown'
        required: true
      category:
        label: 'Category'
        type: 'dropdown'
      tags:
        label: 'Tags'
        type: 'association'
      published_date:
        label: 'Published Date'
        type: 'datepicker'
