views:
  profile:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      basics_header:
        type: 'header'
        text: 'The Basics'
      avatar:
        label: 'Avatar'
        type: 'image'
        size: ['600','600']
      cover:
        label: 'Cover Picture'
        type: 'image'
        size: ['2560','1456']
      first_name:
        label: 'First Name'
        type: 'string'
        maxlength: '50'
        hint: 'Limited to 50 Characters'
      last_name:
        label: 'Last Name'
        type: 'string'
        maxlength: '50'
        hint: 'Limited to 50 Characters'
      bio:
        label: 'Bio'
        type: 'text'
      job:
        label: 'Job Title'
        type: 'string'
      education:
        label: 'Education'
        type: 'string'

      social_header:
        type: 'header'
        text: 'Social'
      url:
        label: 'Website'
        type: 'string'
        maxlength: '200'
      twitter:
        label: 'Twitter Username'
        type: 'string'
        maxlength: '200'
      instagram:
        label: 'Instagram Username'
        type: 'string'
        maxlength: '200'
