views:
  profiles:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      basics_header:
        type: 'header'
        text: 'The Basics'
      avatar:
        label: 'Avatar'
        type: 'image'
        size: ['600','600']
      cover:
        label: 'Cover Picture'
        type: 'image'
        size: ['2560','1456']
      first_name:
        label: 'First Name'
        type: 'string'
        maxlength: '50'
        hint: 'Limited to 50 Characters'
      last_name:
        label: 'Last Name'
        type: 'string'
        maxlength: '50'
        hint: 'Limited to 50 Characters'

      social_header:
        type: 'header'
        text: 'Social'
      url:
        label: 'Website'
        type: 'string'
        maxlength: '200'
      twitter:
        label: 'Twitter Username'
        type: 'string'
        maxlength: '200'
      instagram:
        label: 'Instagram Username'
        type: 'string'
        maxlength: '200'

      comment_header:
        type: 'header'
        text: 'Commenting'
      title:
        label: 'Title'
        type: 'string'
        maxlength: '50'
      location:
        label: 'Location'
        type: 'string'
        maxlength: '50'
      age:
        label: 'Age'
        type: 'integer'
        maxlength: '200'
      signature:
        label: 'Forum Signature'
        type: 'string'
        maxlength: '200'

