views:
  profile:
    new:
      basics_header:
        type: 'header'
        text: 'Basics'
      avatar:
        label: 'Avatar'
        type: 'image'
        size: ['600','600']
      title:
        label: 'Title'
        type: 'string'
        maxlength: '50'
        hint: 'Limited to 50 Characters'
      location:
        label: 'Location'
        type: 'string'
        maxlength: '50'
        hint: 'Limited to 50 Characters'
      age:
        label: 'Age'
        type: 'integer'
        maxlength: '200'
        hint: 'Limited to 200 Characters'
      signature:
        label: 'Signature'
        type: 'string'
        maxlength: '200'
        hint: 'Limited to 200 Characters'
      url:
        label: 'Your Website'
        type: 'string'
        maxlength: '200'

      social_header:
        type: 'header'
        text: 'Social Media'
      twitter:
        label: 'Twitter Username'
        type: 'string'
        maxlength: '200'
        hint: 'Dont include the @'
      instagram:
        label: 'Instagram Username'
        type: 'string'
        maxlength: '200'
        hint: 'Dont include the @'

      branding_header:
        type: 'header'
        text: 'Branding'

      menu_color:
        label: 'Menu Color'
        type: 'color'

      card_color:
        label: 'Card Color'
        type: 'color'
