views:
  tag:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      configuration_header:
        type: 'header'
        text: 'Configuration'
      name:
        label: 'Name'
        type: 'string'
        maxlength: '25'
        hint: 'Limited to 25 Characters'
    list:
      name:
        label: 'Name'
        type: 'string'
    basiclist:
      name:
        label: 'Name'
        type: 'string'
    show:
      configuration_header:
        type: 'header'
        text: 'Configuration'
      name:
        label: 'Name'
        type: 'string'

