views:
  users:
    config:
      set_defaults: false
      rejected_field_names: 'name slug published_date'
    new:
      email:
        label: 'Email'
        type: 'string'
      roles:
        label: 'Role'
        type: 'association_dropdown'
    list:
      email:
        label: 'Email'
        type: 'string'
      created_at:
        label: 'Joined'
        type: 'date'
      roles:
        label: 'Role'
        type: 'unlinked_list'
    basiclist:
      email:
        label: 'Email'
        type: 'string'
      created_at:
        label: 'Joined'
        type: 'date'
      roles:
        label: 'Role'
        type: 'unlinked_list'
    show:
      meta_header:
        type: 'header'
        text: 'Meta'
      email:
        label: 'Email'
        type: 'string'
      created_at:
        label: 'Joined'
        type: 'date'
      roles:
        label: 'Role'
        type: 'unlinked_list'
      profile_header:
        type: 'header'
        text: 'Profile'
      username:
        label: 'User Name'
        type: 'string'
      verified:
        label: 'Verified Profile'
        type: 'string'
        association: 'profile'
      avatar_with_default:
        label: 'Avatar'
        type: 'image'
        association: 'profile'
      title:
        label: 'Title'
        type: 'string'
        association: 'profile'
