import '../semantic/dist/semantic.css'
import '../shared/css/admin/init.sass'
import 'pickadate-webpack/lib/themes/classic.css'
import 'pickadate-webpack/lib/themes/classic.date.css'
import 'pickadate-webpack/lib/themes/classic.time.css'
