views:
  site_settings_theme_authentication:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      sign_up_title:
        advanced: true
        label: '"Sign up" Title'
        type: 'string'
        hint: 'Title of the Sign Up Box'
        required: true
        default: 'Sign Up'

      sign_up_subtitle:
        advanced: true
        label: '"Sign Up" sub title'
        type: 'string'
        hint: 'Sub Title of the Sign Up Box'
        required: true
        default: 'Join The Community'

      sign_in_title:
        advanced: true
        label: '"Sign in" title'
        type: 'string'
        hint: 'Title of the Sign In Box'
        required: true
        default: 'Sign In'

      auth_background:
        label: 'Authentication'
        type: 'image'
        size: ['2560','1600']
        required: true
        default: 'logo.png'
