views:
  site_settings_theme_authentication:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      configuration_header:
        type: 'header'
        text: 'Configuration'
      sign_up_title:
        label: '"Sign Up" Title'
        type: 'string'
        hint: 'Title of the Sign Up Box'
        required: true
        default: 'Sign Up'

      sign_up_subtitle:
        label: '"Sign Up" Sub-title'
        type: 'string'
        hint: 'Sub Title of the Sign Up Box'
        required: true
        default: 'Join The Community'

      sign_in_title:
        label: '"Sign In" Title'
        type: 'string'
        hint: 'Title of the Sign In Box'
        required: true
        default: 'Sign In'

      images_header:
        type: 'header'
        text: 'Images'
      auth_background:
        label: 'Authentication Background'
        type: 'image'
        size: ['2560','1600']
        required: true
        default: 'logo.png'
