views:
  site_settings_theme_branding:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      logo:
        label: 'Logo'
        type: 'image'
        required: true
        default: 'logo.png'
      inverted_logo:
        label: 'Inverted Logo'
        type: 'image'
        required: true
        default: 'logo_inverted.png'
      icon:
        label: 'Icon'
        type: 'image'
        size: ['180','180']
        required: true
        default: 'icon.png'
