views:
  site_settings_theme_branding:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      platform_header:
        type: 'header'
        text: 'Platform'
      logo:
        label: 'Logo'
        type: 'image'
        required: true
        default: 'logo.png'
      inverted_logo:
        label: 'Inverted Logo'
        type: 'image'
        required: true
        default: 'logo_inverted.png'
      icon:
        label: 'Icon'
        type: 'image'
        size: ['180','180']
        required: true
        default: 'icon.png'
      inverted_icon:
        label: 'Inverted Icon'
        type: 'image'
        size: ['180','180']
        required: true
        default: 'icon.png'
      app_header:
        type: 'header'
        text: 'App'
      app_icon:
        label: 'App Icon'
        type: 'image'
        size: ['512','512']
        required: true
        default: 'icon.png'
