views:
  site_settings_theme_discussion:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      nav_header:
        type: 'header'
        text: 'Navigation'
      menu_style:
        advanced: true
        label: 'Menu Background'
        type: 'fixed_dropdown'
        options:
        - solid
        - transparent
        default: 'transparent'
