views:
  site_settings_theme_footer:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      styling_header:
        type: 'header'
        text: 'Styling'

      color:
        label: 'Color'
        type: 'color'
        required: true
        default: 'black'

      button_color:
        advanced: true
        label: 'Button Color'
        type: 'color'
        required: true
        default: 'white'

      button_style:
        advanced: true
        label: 'Button Style'
        type: 'fixed_dropdown'
        options:
        - regular
        - inverted
        required: true
        default: 'regular'

      icon:
        advanced: true
        label: 'Icon'
        type: 'fixed_dropdown'
        options:
        - show
        - hide
        required: true
        default: 'show'

      item_order:
        advanced: true
        label: 'Column Order'
        type: 'fixed_dropdown'
        options:
        - auto
        - reversed
        required: true
        default: 'auto'

      content_header:
        type: 'header'
        text: 'Content'

      about:
        label: 'About Us'
        type: 'rich'
        hint: 'Write two short paragraphs describing the web site.'
        required: true
        default: '<p>Lorem ipsum dolor sit amet</p>'

      copyrights:
        label: 'Copyrights'
        type: 'string'
        required: true
        default: '2017-2018 Logik'
