views:
  site_settings_theme_footer:
    new:
      styling_header:
        type: 'header'
        text: 'Styling'

      color:
        label: 'Color'
        type: 'color'
        required: true

      button_color:
        advanced: true
        label: 'Button Color'
        type: 'color'
        required: true

      button_style:
        advanced: true
        label: 'Button Style'
        type: 'fixed_dropdown'
        options:
        - regular
        - inverted
        required: true

      icon:
        advanced: true
        label: 'Icon'
        type: 'fixed_dropdown'
        options:
        - show
        - hide
        required: true

      item_order:
        advanced: true
        label: 'Column Order'
        type: 'fixed_dropdown'
        options:
        - auto
        - reversed
        required: true

      content_header:
        type: 'header'
        text: 'Content'

      about:
        label: 'About Us'
        type: 'rich'
        hint: 'Write two short paragraphs describing the web site.'
        required: true

      copyrights:
        label: 'Copyrights'
        type: 'string'
        required: true
