views:
  site_settings_theme_footer:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      styling_header:
        type: 'header'
        text: 'Styling'

      color:
        label: 'Color'
        type: 'color'
        required: true
        default: 'black'

      item_order:
        advanced: true
        label: 'Column Order'
        type: 'fixed_dropdown'
        options:
        - auto
        - reversed
        required: true
        default: 'auto'

      content_header:
        type: 'header'
        text: 'Content'

      copyright:
        label: 'Copyrights'
        type: 'string'
        required: true
        default: '&copy; 2019 GoodLogik'
