views:
  site_settings_theme_global:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      configuration_header:
        advanced: true
        type: 'header'
        text: 'Configuration'

      overlay_background:
        advanced: true
        label: 'Overlay Background Style'
        type: 'fixed_dropdown'
        options:
        - normal
        - fixed
        required: true
        default: 'normal'
