views:
  site_settings_theme_header:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      nav_header:
        type: 'header'
        text: 'Navigation'
      menu_color:
        label: 'Background Color'
        type: 'color'
        required: true
        default: 'black'

      button_color:
        label: 'Button Color'
        type: 'color'
        required: true
        default: 'black'

      menu_position:
        label: 'Hamburger Position'
        type: 'fixed_dropdown'
        options:
        - 'left'
        - 'right'
        required: true
        default: 'left'

      logo_header:
        type: 'header'
        text: 'Logo Width'

      desktop_logo_size:
        label: 'Desktop Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'
        default: 150

      mobile_logo_size:
        label: 'Mobile Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'
        default: 120
