views:
  site_settings_theme_header:
    new:
      nav_header:
        type: 'header'
        text: 'Navigation'
      menu_color:
        label: 'Color'
        type: 'color'
        required: true

      button_color:
        advanced: true
        label: 'Button Color'
        type: 'color'
        required: true

      menu_position:
        advanced: true
        label: 'Menu Position'
        type: 'fixed_dropdown'
        options:
        - 'left'
        - 'right'
        required: true

      logo_header:
        type: 'header'
        text: 'Logo'

      desktop_logo_size:
        advanced: true
        label: 'Desktop Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'

      mobile_logo_size:
        advanced: true
        label: 'Mobile Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'
