views:
  site_settings_theme_homepage:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      configuration_header:
        type: 'header'
        text: 'Configuration'
      menu_color:
        label: 'Menu Color'
        type: 'color'
        default: 'black'

      overlay_color:
        label: 'Overlay Color'
        type: 'color'
        default: 'black'

      overlay_background:
        advanced: true
        label: 'Overlay Background'
        type: 'fixed_dropdown'
        options:
        - normal
        - gradient
        default: 'normal'

      image_style:
        advanced: true
        label: 'Image Style'
        type: 'fixed_dropdown'
        options:
        - normal
        - fixed
        default: 'normal'

      category_style:
        advanced: true
        label: 'Category Style'
        type: 'fixed_dropdown'
        options:
        - normal
        - divided
        - white boxed
        - black boxed
        default: 'normal'

      item_order:
        advanced: true
        label: 'Featured Items Order'
        type: 'fixed_dropdown'
        options:
        - auto
        - reversed
        default: 'auto'

      featured_items:
        advanced: true
        label: 'Featured Items'
        type: 'fixed_dropdown'
        options:
        - 1
        - 2
        - 3
        - 4
        - 5
        default: 5

      discussion_items:
        advanced: true
        label: 'Discussion Items'
        type: 'fixed_dropdown'
        options:
        - 3
        - 6
        default: 6

      content_top_padding:
        advanced: true
        label: 'Content Top Padding'
        type: 'integer'
        hint: '(In EM)'
        default: 0

      content_icons:
        advanced: true
        label: 'Content Icons'
        type: 'fixed_dropdown'
        options:
        - show
        - hide
        default: 'show'

      comment_count:
        advanced: true
        label: 'Comment Count'
        type: 'fixed_dropdown'
        options:
        - show
        - hide
        default: 'hide'
