views:
  site_settings_theme_podcast:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      menu_style:
        advanced: true
        label: 'Menu Style'
        type: 'fixed_dropdown'
        options:
        - solid
        - transparent
        - matching solid
        - matching transparent
        default: 'transparent'
        required: true
