views:
  site_settings_branding:
    new:
      branding_header:
        type: 'header'
        text: 'Logos'
      icon:
        label: 'Icon'
        type: 'image'
        size: ['180','180']
      logo:
        label: 'Logo'
        type: 'image'
      inverted_logo:
        label: 'Inverted Logo'
        type: 'image'
      desktop_logo_size:
        advanced: true
        label: 'Desktop Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'
      mobile_logo_size:
        advanced: true
        label: 'Mobile Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'

      background_header:
        type: 'header'
        text: 'Backgrounds'
      auth_background:
        label: 'Authentication'
        type: 'image'
        size: ['2560','1600']
