views:
  site_settings_component:
    new:
      contact_header:
        type: 'header'
        text: 'Contact Info'
      articles:
        label: 'Articles'
        type: 'string'
        maxlength: '20'
        hint: 'Limited to 20 Characters'
