views:
  site_settings_contact:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      contact_header:
        type: 'header'
        text: 'Contact Info'
      phone:
        label: 'Phone'
        type: 'string'
        maxlength: '20'
        hint: 'Limited to 20 Characters'
        default: "800.608.5963"
      email:
        label: 'Email'
        type: 'string'
        default: 'support@goodlogik.com'
      website:
        label: 'Website'
        type: 'string'
        default: 'https://www.goodlogik.com'
      address1:
        label: 'Address 1'
        type: 'string'
        default: '2 E. Congress St'
      address2:
        label: 'Address 2'
        type: 'string'
        default: 'Suite 900'
      address3:
        label: 'Address 3'
        type: 'string'
        default: 'Tucson, AZ 85701'

      social_header:
        type: 'header'
        text: 'Social Media'
      twitter:
        label: 'Twitter Account'
        type: 'string'
        hint: 'include the @'
        default: '@the_idealogic'
      facebook:
        label: 'Facebook Page'
        type: 'string'
        hint: 'Full URL for the Facebook Page. Must start with https://'
        default: "https://www.facebook.com/theidealogic"
