views:
  sitesettings_general:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      configuration_header:
        type: 'header'
        text: 'Configuration'
      name:
        label: 'Platform Name'
        type: 'string'
        hint: 'Used in page title generation. Critical for SEO.'
        default: 'Logik'
        required: true
      legal_name:
        label: 'Legal Name'
        type: 'string'
        hint: 'Used in privacy policy.'
        default: 'Logik'
        required: true
      description:
        label: 'Description'
        type: 'string'
        default: 'Content Publishing Platform'
        required: true
      url:
        label: 'URL'
        type: 'string'
        hint: 'Must start with https://'
        default: 'https://post.goodlogik.com'
        required: true
