views:
  site_settings_integration:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      webhook_header:
        type: 'header'
        text: 'Webhooks'
      newsletter_webhook:
        label: 'Newsletter Subscription'
        type: 'string'
        hint: 'Zapier Webohook URL. Must start with https://'
        default: 'https://hooks.zapier.com/hooks/catch/3200901/fsym7e/'
