views:
  site_settings_theme:
    new:

      ####################
      ####################

      ## Global ##

      ####################
      ####################

      global_header:
        advanced: true
        type: 'header'
        text: 'Global Settings'

      header_font:
        advanced: true
        label: 'Header Font'
        type: 'fixed_dropdown'
        options:
          - Lato
          - Relevay
          - Roboto

      body_font:
        advanced: true
        label: 'Body Font'
        type: 'fixed_dropdown'
        options:
          - Lato
          - Relevay
          - Roboto

      overlay_background:
        advanced: true
        label: 'Overlay Background Style'
        type: 'fixed_dropdown'
        options:
          - auto
          - fixed


      ####################
      ####################

      ## Homepage ##

      ####################
      ####################


      homepage_header:
        type: 'header'
        text: 'Homepage'

      homepage_menu_color:
        label: 'Menu Color'
        type: 'color'

      homepage_overlay_color:
        label: 'Overlay Color'
        type: 'color'

      homepage_overlay_background:
        advanced: true
        label: 'Overlay Background'
        type: 'fixed_dropdown'
        options:
          - normal
          - gradient

      content_icons:
        advanced: true
        label: 'Content Icons'
        type: 'fixed_dropdown'
        options:
          - show
          - hide

      comment_count:
        advanced: true
        label: 'Comment Count'
        type: 'fixed_dropdown'
        options:
          - show
          - hide

      homepage_category_style:
        advanced: true
        label: 'Category Style'
        type: 'fixed_dropdown'
        options:
          - normal
          - divided
          - white boxed
          - black boxed

      homepage_item_order:
        advanced: true
        label: 'Featured Items Order'
        type: 'fixed_dropdown'
        options:
          - auto
          - reversed

      homepage_featured_variant:
        advanced: true
        label: 'Featured Widget Variant'
        type: 'fixed_dropdown'
        options:
          - a
          - b

      homepage_featured_items:
        advanced: true
        label: 'Featured Items'
        type: 'fixed_dropdown'
        options:
          - 1
          - 2
          - 3
          - 4
          - 5

      homepage_discussion_items:
        advanced: true
        label: 'Discussion Items'
        type: 'fixed_dropdown'
        options:
          - 3
          - 6

      homepage_content_top_padding:
        advanced: true
        label: 'Content Top Padding'
        type: 'integer'
        hint: '(In EM)'


      ####################
      ####################

      ## Discussions ##

      ####################
      ####################


      discussions_header:
        type: 'header'
        text: 'Discussions'


      discussion_menu_style:
        advanced: true
        label: 'Menu Style'
        type: 'fixed_dropdown'
        options:
          - solid
          - transparent
          - matching

      ####################
      ####################

      ## Navigation ##

      ####################
      ####################


      header_header:
        type: 'header'
        text: 'Header'

      menu_color:
        label: 'Color'
        type: 'color'

      menu_position:
        advanced: true
        label: 'Menu Position'
        type: 'fixed_dropdown'
        options:
          - 'left'
          - 'right'

      desktop_logo_size:
        advanced: true
        label: 'Desktop Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'

      mobile_logo_size:
        advanced: true
        label: 'Mobile Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'


      ####################
      ####################

      ## Footer ##

      ####################
      ####################


      footer_header:
        type: 'header'
        text: 'Footer'

      footer_variant:
        advanced: true
        label: 'Variant'
        type: 'fixed_dropdown'
        options:
          - full
          - slim

      footer_color:
        label: 'Color'
        type: 'color'

      footer_button_color:
        advanced: true
        label: 'Button Color'
        type: 'color'

      footer_button_style:
        advanced: true
        label: 'Button Style'
        type: 'fixed_dropdown'
        options:
          - regular
          - inverted

      footer_icon:
        advanced: true
        label: 'Icon'
        type: 'fixed_dropdown'
        options:
          - show
          - hide

      footer_item_order:
        advanced: true
        label: 'Column Order'
        type: 'fixed_dropdown'
        options:
          - auto
          - reversed

      about:
        label: 'About Us'
        type: 'rich'
        hint: 'Write two short paragraphs describing the web site.'

      copyrights:
        label: 'Copyrights'
        type: 'string'


      ####################
      ####################

      ## Authentication ##

      ####################
      ####################


      auth_header:
        advanced: true
        type: 'header'
        text: 'Authentication'

      sign_up_title:
        advanced: true
        label: '"Sign up" Title'
        type: 'string'
        hint: 'Title of the Sign Up Box'

      sign_up_subtitle:
        advanced: true
        label: '"Sign Up" sub title'
        type: 'string'
        hint: 'Sub Title of the Sign Up Box'

      sign_in_title:
        advanced: true
        label: '"Sign In" title'
        type: 'string'
        hint: 'Title of the Sign In Box'
