views:
  site_settings_theme:
    new:
      global_header:
        advanced: true
        type: 'header'
        text: 'Global Settings'
      content_icons:
        advanced: true
        label: 'Content Icons'
        type: 'fixed_dropdown'
        options:
          - show
          - hide
      comment_count:
        advanced: true
        label: 'Comment Count'
        type: 'fixed_dropdown'
        options:
          - show
          - hide
      overlay_background:
        advanced: true
        label: 'Overlay Background'
        type: 'fixed_dropdown'
        options:
          - auto
          - fixed

      homepage_header:
        type: 'header'
        text: 'Homepage'
      homepage_menu_color:
        label: 'Menu Color'
        type: 'color'
      homepage_overlay_color:
        label: 'Overlay Color'
        type: 'color'
      homepage_overlay_background:
        advanced: true
        label: 'Overlay Background'
        type: 'fixed_dropdown'
        options:
          - normal
          - gradient
      homepage_category_style:
        advanced: true
        label: 'Category Style'
        type: 'fixed_dropdown'
        options:
          - normal
          - divided
          - white boxed
          - black boxed
      homepage_item_order:
        advanced: true
        label: 'Featured Items Order'
        type: 'fixed_dropdown'
        options:
          - auto
          - reversed
      homepage_featured_items:
        advanced: true
        label: 'Featured Items'
        type: 'fixed_dropdown'
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
      homepage_discussion_items:
        advanced: true
        label: 'Discussion Items'
        type: 'fixed_dropdown'
        options:
          - 3
          - 6
      homepage_content_top_padding:
        advanced: true
        label: 'Content Top Padding'
        type: 'integer'
        hint: '(In EM)'

      header_header:
        type: 'header'
        text: 'Header'
      menu_color:
        label: 'Color'
        type: 'color'
      menu_position:
        advanced: true
        label: 'Menu Position'
        type: 'fixed_dropdown'
        options:
          - 'left'
          - 'right'
      desktop_logo_size:
        advanced: true
        label: 'Desktop Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'
      mobile_logo_size:
        advanced: true
        label: 'Mobile Logo Width'
        type: 'string'
        hint: '(in pixels)'
        maxlength: '3'

      footer_header:
        type: 'header'
        text: 'Footer'
      footer_color:
        label: 'Color'
        type: 'color'
      footer_button_color:
        advanced: true
        label: 'Button Color'
        type: 'color'
      footer_icon:
        advanced: true
        label: 'Icon'
        type: 'fixed_dropdown'
        options:
          - show
          - hide
      footer_item_order:
        advanced: true
        label: 'Column Order'
        type: 'fixed_dropdown'
        options:
          - auto
          - reversed

      about:
        label: 'About Us'
        type: 'rich'
        hint: 'Write two short paragraphs describing the web site.'
      copyrights:
        label: 'Copyrights'
        type: 'string'

      auth_header:
        advanced: true
        type: 'header'
        text: 'Authentication'
      sign_up_title:
        advanced: true
        label: '"Sign up" Title'
        type: 'string'
        hint: 'Title of the Sign Up Box'
      sign_up_subtitle:
        advanced: true
        label: '"Sign Up" sub title'
        type: 'string'
        hint: 'Sub Title of the Sign Up Box'
      sign_in_title:
        advanced: true
        label: '"Sign In" title'
        type: 'string'
        hint: 'Title of the Sign In Box'

    show:
      global_header:
        advanced: true
        type: 'header'
        text: 'Global Settings'
      content_icons:
        advanced: true
        label: 'Content Icons'
        type: 'string'
      comment_count:
        advanced: true
        label: 'Comment Count'
        type: 'string'
      overlay_background:
        advanced: true
        label: 'Overlay Background'
        type: 'string'

      homepage_header:
        type: 'header'
        text: 'Homepage'
      homepage_menu_color:
        label: 'Menu Color'
        type: 'plain_color'
      homepage_overlay_color:
        label: 'Overlay Color'
        type: 'plain_color'
      homepage_overlay_background:
        advanced: true
        label: 'Overlay Background'
        type: 'string'
      homepage_item_order:
        advanced: true
        label: 'Featured Items Order'
        type: 'string'
      homepage_featured_items:
        advanced: true
        label: 'Featured Items'
        type: 'string'
      homepage_discussion_items:
        advanced: true
        label: 'Discussion Items'
        type: 'string'
      homepage_content_top_padding:
        advanced: true
        label: 'Content Top Padding'
        type: 'string'

      navigation_header:
        type: 'header'
        text: 'Navigation'
      menu_color:
        label: 'Menu Color'
        type: 'plain_color'
      menu_position:
        advanced: true
        label: 'Menu Position'
        type: 'string'
      desktop_logo_size:
        advanced: true
        label: 'Desktop Logo Width'
        type: 'string'
      mobile_logo_size:
        advanced: true
        label: 'Mobile Logo Width'
        type: 'string'

      footer_header:
        type: 'header'
        text: 'Footer'
      footer_color:
        label: 'Color'
        type: 'plain_color'
      footer_button_color:
        advanced: true
        label: 'Button Color'
        type: 'plain_color'
      footer_icon:
        advanced: true
        label: 'Icon'
        type: 'string'
      footer_item_order:
        advanced: true
        label: 'Column Order'
        type: 'string'
      about:
        label: 'About Us'
        type: 'string'
      copyrights:
        label: 'Copyrights'
        type: 'string'

      auth_header:
        advanced: true
        type: 'header'
        text: 'Authentication'
      sign_up_title:
        advanced: true
        label: 'Sign Up Title'
        type: 'string'
      sign_up_subtitle:
        advanced: true
        label: 'Sign Sub Title'
        type: 'string'
      sign_in_title:
        advanced: true
        label: 'Sign In Title'
        type: 'string'
