defaults: &defaults
  public_key: <%= ENV["UPLOADCARE_PUBLIC_KEY"] %>
  private_key: <%= ENV["UPLOADCARE_PRIVATE_KEY"] %>

development:
  <<: *defaults

test:
  <<: *defaults
  autostore: false

production:
  <<: *defaults

