views:
  elements_blockquote:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      author:
        label: 'Author'
        icon: 'heading'
        type: 'string'
      body:
        label: 'Summary'
        icon: 'text width'
        type: 'text'
      alignment:
        label: 'Alignment'
        type: 'fixed_dropdown'
        icon: 'align left'
        default: 'left'
        options:
          - 'left'
          - 'centered'
          - 'right'
        advanced: true
