views:
  elements_divider:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      header:
        label: 'Heading'
        icon: 'heading'
        type: 'string'
      icon:
        label: 'Divider Icon'
        icon: 'bolt'
        type: 'fixed_dropdown'
        options:
          - 'angle down'
          - 'angle double down'
          - 'flag checkered'
          - 'heart'
