views:
  elements_embededheader:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      title:
        label: 'Title'
        type: 'string'
        maxlength: '85'
        hint: 'Limited to 85 characters'
      title_alignment:
        label: 'Alignment'
        type: 'fixed_dropdown'
        icon: 'align left'
        options:
          - 'left'
          - 'centered'
          - 'right'
          - 'justified'
        advanced: true
      url:
        label: 'URL'
        type: 'string'
        hint: 'Link to Embed'
      color:
        label: 'Background'
        type: 'color'
        default: 'black'
