views:
  elements_embed:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      url:
        label: 'URL'
        icon: 'globe'
        type: 'string'
        hint: 'URL to be Embedded'
