views:
  elements_embededheader:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      url:
        label: 'URL'
        type: 'string'
        hint: 'URL to be Embedded'
      color:
        label: 'Background Color'
        type: 'color'
        default: 'black'
