views:
  elements_heading:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      header:
        label: 'Header'
        type: 'string'
      subheader:
        label: 'Sub-header'
        type: 'string'
      size:
        label: 'Size'
        type: 'fixed_dropdown'
        options:
          - 'H1'
          - 'H2'
          - 'H3'
          - 'H4'
          - 'H5'
