views:
  elements_heading:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      header:
        label: 'Header'
        type: 'string'
      subheader:
        label: 'Sub-header'
        type: 'string'