views:
  elements_heading:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      header:
        label: 'Heading Text'
        type: 'string'
      subheader:
        label: 'Sub-Heading Text'
        type: 'string'
        advanced: true
      size:
        label: 'Text Size'
        type: 'fixed_dropdown'
        options:
          - 'H1'
          - 'H2'
          - 'H3'
          - 'H4'
          - 'H5'
