views:
  elements_heading:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      header:
        label: 'Heading'
        icon: 'heading'
        type: 'string'
      subheader:
        label: 'Sub-Heading'
        icon: 'font'
        type: 'string'
        advanced: true
      size:
        label: 'Size'
        icon: 'text height'
        type: 'fixed_dropdown'
        options:
          - 'H1'
          - 'H2'
          - 'H3'
          - 'H4'
          - 'H5'
