views:
  elements_imageheader:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      title:
        label: 'Title'
        type: 'string'
        maxlength: '85'
        hint: 'Limited to 85 characters'
      title_alignment:
        label: 'Title Alignment'
        type: 'fixed_dropdown'
        options:
          - 'left'
          - 'centered'
          - 'right'
          - 'justified'
      summary:
        label: 'Summary'
        type: 'text'
      summary_alignment:
        label: 'Summary Alignment'
        type: 'fixed_dropdown'
        options:
          - 'left'
          - 'centered'
          - 'right'
          - 'justified'
      landscape_image:
        label: 'Background Landscape Image'
        type: 'image'
        size: ['2560','1456']
      vertical_image:
        label: 'Background Vertical Image'
        type: 'image'
        size: ['1456','2560']
      alt_text:
        label: 'Image Description'
        type: 'string'
        hint: 'Describe the image for visually impaired, i.e. a horse eating a carrot.'
