views:
  elements_image:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      image:
        label: 'Image'
        icon: 'image'
        type: 'image'
      alt_text:
        label: 'Description'
        icon: 'image'
        type: 'string'
        hint: 'Describe the image for visually impaired, i.e. a horse eating a carrot.'
      size:
        label: 'Size'
        icon: 'image'
        type: 'fixed_dropdown'
        options:
          - fluid
          - big
          - large
          - medium
          - small
          - mini
          - tiny
        advanced: true
      alignment:
        label: 'Alignment'
        icon: 'image'
        type: 'fixed_dropdown'
        options:
          - left
          - centered
          - right
      style:
        label: 'Style'
        icon: 'image'
        type: 'fixed_dropdown'
        options:
          - none
          - bordered
          - rounded
          - circular
        advanced: true
      caption:
        label: 'Caption'
        icon: 'text width'
        type: 'string'
