views:
  elements_imageheader:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      title:
        label: 'Title'
        type: 'string'
        maxlength: '85'
        hint: 'Limited to 85 characters'
      summary:
        label: 'Summary'
        type: 'text'
      landscape_image:
        label: 'Landscape Image'
        type: 'image'
        size: ['2560','1456']
