views:
  elements_oversizedquote:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      summary:
        label: 'Quote'
        icon: 'heading'
        type: 'text'
      credit:
        label: 'Author'
        icon: 'text width'
        type: 'string'
      landscape_image:
        label: 'Desktop Background'
        type: 'image'
        icon: 'image'
        size: ['2560','1456']
      vertical_image:
        label: 'Mobile Background'
        icon: 'image'
        type: 'image'
        size: ['1456','2560']
      overlay_background:
        advanced: true
        label: 'Background Style'
        type: 'fixed_dropdown'
        options:
          - normal
          - fixed
        default: 'normal'
      alt_text:
        label: 'Background Description'
        icon: 'image'
        type: 'string'
        hint: 'Describe the image for visually impaired (i.e. a horse eating a carrot).'
