views:
  elements_oversizedquote:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      summary:
        label: 'Quote'
        type: 'text'
      credit:
        label: 'Author'
        type: 'string'
      landscape_image:
        label: 'Background Landscape Image'
        type: 'image'
        size: ['2560','1456']
      vertical_image:
        label: 'Background Vertical Image'
        type: 'image'
        size: ['1456','2560']
      alt_text:
        label: 'Alt. Text'
        type: 'string'
        hint: 'Describe the image for visually impaired'
