views:
  elements_oversizedimage:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      title:
        label: 'Title'
        type: 'string'
        maxlength: '85'
        hint: 'Limited to 85 characters'
      title_alignment:
        label: 'Alignment'
        type: 'fixed_dropdown'
        options:
          - 'left'
          - 'centered'
          - 'right'
          - 'justified'
        advanced: true
      summary:
        label: 'Caption'
        type: 'text'
      summary_alignment:
        label: 'Alignment'
        type: 'fixed_dropdown'
        options:
          - 'left'
          - 'centered'
          - 'right'
          - 'justified'
        advanced: true
      landscape_image:
        label: 'Desktop Background'
        type: 'image'
        icon: 'image'
        size: ['2560','1456']
      vertical_image:
        label: 'Mobile Background'
        icon: 'image'
        type: 'image'
        size: ['1456','2560']
      alt_text:
        label: 'Image Description'
        type: 'string'
        hint: 'Describe the image for visually impaired (i.e. a horse eating a carrot).'
