views:
  elements_oversizedembed:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      title:
        label: 'Title'
        type: 'string'
        maxlength: '85'
        hint: 'Limited to 85 characters'
      title_alignment:
        label: 'Alignment'
        type: 'fixed_dropdown'
        options:
          - 'left'
          - 'centered'
          - 'right'
          - 'justified'
      url:
        label: 'URL'
        type: 'string'
        hint: 'URL to be Embedded'
      color:
        label: 'Background Color'
        type: 'color'
        default: 'black'
