views:
  elements_richtext:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      rich:
        label: 'Text'
        icon: 'list ul'
        type: 'rich'
      alignment:
        label: 'Alignment'
        type: 'fixed_dropdown'
        icon: 'align left'
        options:
          - 'left'
          - 'centered'
          - 'right'
