views:
  elements_videoheader:
    config:
      set_defaults: true
      rejected_field_names: ''
    new:
      title:
        label: 'Title'
        icon: 'heading'
        type: 'string'
        maxlength: '50'
        hint: 'Limited to 50 characters'
      video:
        label: 'Video'
        icon: 'video'
        type: 'video'
      video_description:
        label: 'Video Description'
        icon: 'video'
        type: 'string'
        hint: 'Short description of what the video is about.'
      video_cover:
        label: 'Video Cover'
        icon: 'image'
        type: 'image'
        size: ['1972','1110']
      landscape_image:
        label: 'Desktop Background'
        type: 'image'
        icon: 'image'
        size: ['2560','1456']
      vertical_image:
        label: 'Mobile Background'
        icon: 'image'
        type: 'image'
        size: ['1456','2560']
      overlay_background:
        advanced: true
        label: 'Background Style'
        type: 'fixed_dropdown'
        options:
          - normal
          - fixed
        default: 'normal'
      alt_text:
        label: 'Background Description'
        icon: 'image'
        type: 'string'
        hint: 'Describe the image for visually impaired (i.e. a horse eating a carrot).'
