menu:
  settings:
    - section:
      - name: General
        hint: Set the platform name, legal name, description, and url.
        path: admin_settings_general
        icon: setting
        enabled: true
      - name: Contact
        hint: Set the mailing address, phone, web and social media.
        path: admin_settings_contact
        icon: address card
        enabled: true
      - name: Theme
        hint: Change the look and feel of the platform.
        path: admin_settings_theme_root
        icon: paint brush
        enabled: true
      - name: Components
        hint: Enable and Disable platform components.
        path: admin_settings_components
        icon: qrcode
        enabled: true
        advanced: true
      - name: Integrations
        hint: Use webhooks to integrate the platform with other services.
        path: admin_settings_integration
        icon: plug
        enabled: true
        advanced: true
